services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-coffine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      - PHP_FPM_USER=apache
      - PHP_FPM_GROUP=apache
    networks:
      - app-network
    # restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: pg-coffine
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/import/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
